import { sponsors, type Sponsor } from "./sponsors";
import { youtubeVideos, type YoutubeVideo } from "./youtube-videos";
import { photoAlbums, type PhotoAlbum } from "./photo-albums";

export type { Sponsor, YoutubeVideo, PhotoAlbum };

export interface Event {
  id: string;
  title: string;
  pitch?: string;
  date: string;
  time?: string;
  venue?: string;
  capacity?: number;
  tags: string[];
  status: "upcoming" | "past";
  /** Event URL — prefers Luma when available, falls back to Meetup */
  eventUrl?: string;
  imagePath?: string;
  photoAlbum?: PhotoAlbum;
  youtubeVideo?: YoutubeVideo;
  host?: Sponsor;
  sponsors?: Sponsor[];
  speakers?: {
    name: string;
    title: string;
    company?: string;
    talkTitle?: string;
    image?: string;
  }[];
}

export const events: Event[] = [
  // ─── Upcoming ────────────────────────────────────────────────────────────────
  {
    id: "supercollider-spring-fling-2026",
    title: "SUPERCOLLIDER Spring Fling — Toronto Tech Communities Networking Night",
    pitch: "Multi-community spring networking night at Left Field Brewery",
    date: "2026-04-27",
    time: "6:00 PM - 9:00 PM",
    venue: "Left Field Brewery (Liberty Village)",
    tags: ["Networking", "Social", "Multi-community"],
    status: "upcoming",
    eventUrl: "https://lu.ma/supercollider-spring-fling-2026",
  },
  {
    id: "code-diversity-coffee-2026-05",
    title: "Code Diversity Monthly Coffee Chats",
    pitch: "Welcoming coffee meetup for women and non-binary folks in tech",
    date: "2026-05-02",
    time: "11:00 AM - 1:00 PM",
    venue: "Prema Coffee and Bar",
    tags: ["CodeDiversity", "Social", "Coffee Chat"],
    status: "upcoming",
    eventUrl: "https://lu.ma/3ea6eq1s",
    imagePath: "/images/luma/bca86cee-3fdb-403a-bb09-ccc095690401.jpg",
  },
  // ─── 2026 ────────────────────────────────────────────────────────────────────
  {
    id: "techtank-turns-3",
    title: "TECHTANK Turns 3",
    pitch: "Celebrating three years of Toronto tech community",
    date: "2026-04-16",
    time: "8:00 PM - 11:00 PM",
    venue: "Dina's Tavern",
    tags: ["Anniversary", "Social"],
    status: "past",
    eventUrl: "https://lu.ma/qwpt54ke",
    photoAlbum: photoAlbums["AF1QipM-VmIz5kOG18HrCZIcQyfVLgKKsCQSS_SWIo2ODM5DME1Z7BEoQOoMD5JbBujfkA"],
  },
  {
    id: "ci-optimization-brainstation",
    title: "CI Optimization: Built-In Flags You're Probably Not Using",
    pitch: "Save CI time with native caching flags your pipeline is missing",
    date: "2026-04-13",
    time: "6:30 PM - 9:00 PM",
    venue: "BrainStation",
    capacity: 100,
    tags: ["Tech Talk", "DevOps", "CI/CD"],
    status: "past",
    eventUrl: "https://lu.ma/7h4g008b",
    sponsors: [sponsors.brainstation],
    photoAlbum: photoAlbums["AF1QipN3f4J0Ya2sv76VCQXhdkKipehavLCc3v4kcdfwqqosjY2jN-KWfT3X4wrqCiRy4w"],
    speakers: [
      {
        name: "Emily Xiong",
        title: "Software Developer",
        company: "Stackadapt",
        talkTitle: "Save CI Time with Built-In Flags",
      },
    ],
  },
  {
    id: "code-diversity-coffee-2026-04",
    title: "Code Diversity Monthly Coffee Chats",
    pitch: "Monthly coffee chat for women and non-binary folks in tech",
    date: "2026-04-11",
    time: "11:00 AM - 1:00 PM",
    venue: "Prema Coffee and Bar",
    tags: ["CodeDiversity", "Social", "Coffee Chat"],
    status: "past",
    eventUrl: "https://lu.ma/cye39lls",
    imagePath: "/images/luma/bca86cee-3fdb-403a-bb09-ccc095690401.jpg",
  },
  {
    id: "code-diversity-iwd-pottery-2026",
    title: "Code Diversity × TigerBaby: IWD Pottery Workshop — Clay & Connection",
    pitch: "International Women's Day pottery workshop for women in tech",
    date: "2026-03-14",
    time: "11:00 AM - 1:00 PM",
    venue: "Creeds Coffee Bar",
    tags: ["CodeDiversity", "Social", "IWD"],
    status: "past",
    eventUrl: "https://lu.ma/wzaj4vzy",
    imagePath: "/images/meetup/highres_532757822.jpeg",
  },
  {
    id: "code-diversity-coffee-2026-01",
    title: "Code Diversity Monthly Coffee Chats",
    pitch: "Monthly coffee chat for women and non-binary folks in tech",
    date: "2026-01-17",
    time: "11:00 AM - 1:00 PM",
    venue: "Prema Coffee and Bar",
    tags: ["CodeDiversity", "Social", "Coffee Chat"],
    status: "past",
    eventUrl: "https://www.meetup.com/techtank-to/events/312122429/",
    imagePath: "/images/meetup/highres_531054652.jpeg",
  },
  // ─── 2025 ────────────────────────────────────────────────────────────────────
  {
    id: "code-diversity-coffee-2025-12",
    title: "Code Diversity Monthly Coffee Chats",
    pitch: "Monthly coffee chat for women and non-binary folks in tech",
    date: "2025-12-20",
    time: "11:00 AM - 1:00 PM",
    venue: "Prema Coffee and Bar",
    tags: ["CodeDiversity", "Social", "Coffee Chat"],
    status: "past",
    eventUrl: "https://www.meetup.com/techtank-to/events/311812267/",
    imagePath: "/images/meetup/highres_531054652.jpeg",
  },
  {
    id: "santacollider-2025",
    title: "Santacollider: Toronto Tech Community Holiday Party",
    pitch: "Annual multi-community holiday party at The Pilot",
    date: "2025-12-09",
    time: "6:00 PM - 10:00 PM",
    venue: "The Pilot",
    tags: ["Social", "Holiday", "Multi-community"],
    status: "past",
    eventUrl: "https://www.meetup.com/techtank-to/events/312122530/",
    imagePath: "/images/meetup/highres_531423712.jpeg",
  },
  {
    id: "code-diversity-coffee-2025-11",
    title: "Code Diversity Monthly Coffee Chats",
    pitch: "Monthly coffee chat for women and non-binary folks in tech",
    date: "2025-11-15",
    time: "11:00 AM - 1:00 PM",
    venue: "Prema Coffee and Bar",
    tags: ["CodeDiversity", "Social", "Coffee Chat"],
    status: "past",
    eventUrl: "https://www.meetup.com/techtank-to/events/311811712/",
    imagePath: "/images/meetup/highres_531054652.jpeg",
  },
  {
    id: "code-diversity-coffee-2025-10",
    title: "Code Diversity Monthly Coffee Chats",
    pitch: "Monthly coffee chat for women and non-binary folks in tech",
    date: "2025-10-18",
    time: "11:00 AM - 1:00 PM",
    venue: "Prema Coffee and Bar",
    tags: ["CodeDiversity", "Social", "Coffee Chat"],
    status: "past",
    eventUrl: "https://www.meetup.com/techtank-to/events/308164572/",
    imagePath: "/images/meetup/highres_524928803.jpeg",
  },
  {
    id: "battle-frameworks-underdog",
    title: "Battle of the Frameworks: Underdog Edition",
    pitch: "Framework showdown with a twist — the underdogs get their moment",
    date: "2025-10-08",
    time: "6:00 PM - 9:00 PM",
    venue: "Rakuten Kobo",
    tags: ["Tech Talk", "Panel", "Frameworks"],
    status: "past",
    eventUrl: "https://www.meetup.com/techtank-to/events/311105172/",
    photoAlbum: photoAlbums["AF1QipPPmVC7Jg5of2zIp8CgLxyavCSvyu-3ekKf_nEVwqqNA3lX4VBuVijVBSvZ62dNng"],
  },
  {
    id: "agentic-programming-7shifts",
    title: "Agentic Programming 101",
    pitch: "Introduction to AI agents and autonomous programming",
    date: "2025-09-29",
    time: "6:00 PM - 9:00 PM",
    venue: "7shifts",
    tags: ["Tech Talk", "AI", "Beginner-friendly"],
    status: "past",
    eventUrl: "https://www.meetup.com/techtank-to/events/310620439/",
    host: sponsors["7shifts"],
    photoAlbum: photoAlbums["AF1QipNHIuIQ3GEwyuE7hRn3rrREKk2jRULCv3DkSatNFoAVgNYpQrzOd3VHmpsbT5L15w"],
  },
  {
    id: "mentorship-meetup-2025",
    title: "Mentorship Meetup: For Tech Talent in Their First 1–5 Years",
    pitch: "Coffee chat and peer mentorship for early-career developers",
    date: "2025-09-13",
    time: "11:00 AM - 1:00 PM",
    venue: "Prema Coffee and Bar",
    tags: ["Mentorship", "Career", "Beginner-friendly"],
    status: "past",
    eventUrl: "https://www.meetup.com/techtank-to/events/310493631/",
    imagePath: "/images/meetup/highres_529607775.jpeg",
  },
  {
    id: "code-diversity-coffee-2025-09",
    title: "Code Diversity Monthly Coffee Chats",
    pitch: "Monthly coffee chat for women and non-binary folks in tech",
    date: "2025-09-06",
    time: "11:00 AM - 1:00 PM",
    venue: "Prema Coffee and Bar",
    tags: ["CodeDiversity", "Social", "Coffee Chat"],
    status: "past",
    eventUrl: "https://www.meetup.com/techtank-to/events/308163824/",
    imagePath: "/images/meetup/highres_528812977.jpeg",
  },
  {
    id: "buns-funds-bbq-2025",
    title: "Buns & Fun(d)s: Flippin' those Burgers with TechTank!",
    pitch: "Summer burger cookout with the TechTank community",
    date: "2025-08-02",
    time: "1:30 PM - 5:00 PM",
    tags: ["Social", "Food", "Summer"],
    status: "past",
    eventUrl: "https://www.meetup.com/techtank-to/events/308895464/",
    imagePath: "/images/meetup/highres_528916938.jpeg",
  },
  {
    id: "code-diversity-coffee-2025-08",
    title: "Code Diversity Monthly Coffee Chats",
    pitch: "Monthly coffee chat for women and non-binary folks in tech",
    date: "2025-08-02",
    time: "11:00 AM - 1:00 PM",
    venue: "Prema Coffee and Bar",
    tags: ["CodeDiversity", "Social", "Coffee Chat"],
    status: "past",
    eventUrl: "https://www.meetup.com/techtank-to/events/308163788/",
    imagePath: "/images/meetup/highres_524928803.jpeg",
  },
  {
    id: "softball-sashimis-2025",
    title: "Softball Sashimis",
    pitch: "TechTank's summer softball game",
    date: "2025-06-21",
    tags: ["Sports", "Social"],
    status: "past",
    photoAlbum: photoAlbums["AF1QipMpnt5xDbFhqPFjq-d3e6NNoGiRUMTXxxbCQ-jTbOPnEE1tx6RMZEDt6s0ILEOetA"],
  },
  {
    id: "supercollider-techweek-2025",
    title: "SUPERCOLLIDER: Toronto Tech Week After Party",
    pitch: "Multi-community after party wrapping up Toronto Tech Week 2025",
    date: "2025-06-27",
    time: "8:00 PM - 11:00 PM",
    venue: "Greta Bar",
    tags: ["Social", "Tech Week", "Multi-community"],
    status: "past",
    eventUrl: "https://www.meetup.com/techtank-to/events/307828751/",
    imagePath: "/images/meetup/highres_527960195.jpeg",
  },
  {
    id: "techweek-codediversity",
    title: "CodeDiversity by TechTank & 7shifts — Toronto Tech Week 2025",
    pitch: "Special CodeDiversity event during Toronto Tech Week at 7shifts HQ",
    date: "2025-06-25",
    time: "6:00 PM - 9:00 PM",
    venue: "7shifts",
    tags: ["CodeDiversity", "Tech Week"],
    status: "past",
    eventUrl: "https://www.meetup.com/techtank-to/events/307623203/",
    photoAlbum: photoAlbums["AF1QipMingUvuBFdNA4ES6wYi3UCHzRT3k9Il3wlWnFoUu_-5X8jztaoTjtAloU7TLIMJg"],
  },
  {
    id: "code-diversity-coffee-2025-05",
    title: "Code Diversity Monthly Coffee Chats",
    pitch: "Monthly coffee chat for women and non-binary folks in tech",
    date: "2025-05-24",
    time: "11:00 AM - 1:00 PM",
    venue: "Prema Coffee and Bar",
    tags: ["CodeDiversity", "Social", "Coffee Chat"],
    status: "past",
    eventUrl: "https://www.meetup.com/techtank-to/events/307465132/",
    imagePath: "/images/meetup/highres_527561328.jpeg",
  },
  {
    id: "anniversary-spinco",
    title: "2nd Anniversary @ SpinCo",
    pitch: "Celebrating two years with spin and socializing",
    date: "2025-04-26",
    venue: "SpinCo",
    tags: ["Anniversary", "Sports", "Social"],
    status: "past",
    photoAlbum: photoAlbums["AF1QipNsmSeqY9wxLMtqnFkDoPaj4X5T-cmuUkYkVHYHPUopyT4-b_IYhiPajDguMT-CSQ"],
  },
  {
    id: "code-diversity-coffee-2025-04",
    title: "Code Diversity Monthly Coffee Chats",
    pitch: "Monthly coffee chat for women and non-binary folks in tech",
    date: "2025-04-26",
    time: "11:00 AM - 1:00 PM",
    venue: "Prema Coffee and Bar",
    tags: ["CodeDiversity", "Social", "Coffee Chat"],
    status: "past",
    eventUrl: "https://www.meetup.com/techtank-to/events/306889689/",
    imagePath: "/images/meetup/highres_524928803.jpeg",
  },
  {
    id: "saas-cloud-migration",
    title: "Lightning Talks: Migrating a SaaS Product across Cloud Providers",
    pitch: "Lightning talks from senior engineers on cloud migration",
    date: "2025-04-10",
    time: "6:00 PM - 9:00 PM",
    venue: "Vena Solutions",
    tags: ["Tech Talk", "Cloud", "Architecture"],
    status: "past",
    eventUrl: "https://www.meetup.com/techtank-to/events/306752010/",
    sponsors: [sponsors.vena],
    speakers: [
      { name: "Saiid Douaihy", title: "Senior Software Manager", talkTitle: "Cloud Migration Strategies" },
      { name: "Pawan Keer", title: "Senior Software Development Manager", talkTitle: "Infrastructure at Scale" },
      { name: "Lucas Tran", title: "Senior Software Developer", talkTitle: "Lessons from the Trenches" },
    ],
    youtubeVideo: youtubeVideos["4MSJq2GBsIc"],
    photoAlbum: photoAlbums["AF1QipOb1lKTP_ktVaptdlB6GndudP3YQ77pW6BR3IxcDA2YV86ZNaHZe3M0Hp2iD6UoLA"],
  },
  {
    id: "code-diversity-coffee-2025-03",
    title: "Code Diversity Monthly Coffee Chats",
    pitch: "Monthly coffee chat for women and non-binary folks in tech",
    date: "2025-03-15",
    time: "11:00 AM - 1:00 PM",
    venue: "Prema Coffee and Bar",
    tags: ["CodeDiversity", "Social", "Coffee Chat"],
    status: "past",
    eventUrl: "https://www.meetup.com/techtank-to/events/306586846/",
    imagePath: "/images/meetup/highres_524928803.jpeg",
  },
  {
    id: "code-diversity-coffee-2025-02",
    title: "Code Diversity Monthly Coffee Chats",
    pitch: "Monthly coffee chat for women and non-binary folks in tech",
    date: "2025-02-15",
    time: "11:00 AM - 1:00 PM",
    venue: "Carbonic Coffee",
    tags: ["CodeDiversity", "Social", "Coffee Chat"],
    status: "past",
    eventUrl: "https://www.meetup.com/techtank-to/events/305857202/",
    imagePath: "/images/meetup/highres_524928803.jpeg",
  },
  {
    id: "cross-browser-extensions-cohere",
    title: "Building Cross-Browser Extensions: Challenges and Best Practices",
    pitch: "Building extensions that work everywhere",
    date: "2025-01-28",
    time: "6:00 PM - 9:00 PM",
    venue: "Cohere",
    tags: ["Tech Talk", "Browser Extensions"],
    status: "past",
    eventUrl: "https://www.meetup.com/techtank-to/events/305400630/",
    host: sponsors.cohere,
    youtubeVideo: youtubeVideos["f8ONw6O_rco"],
    photoAlbum: photoAlbums["AF1QipMrTfiNbI7_NSGioh-DLR6Slvp51pBjf1cShVzeToyKNr982BbkOEPmrqFYhd7vMg"],
  },
  {
    id: "code-diversity-coffee-2025-01",
    title: "Code Diversity Monthly Coffee Chats",
    pitch: "Monthly coffee chat for women and non-binary folks in tech",
    date: "2025-01-11",
    time: "11:00 AM - 1:00 PM",
    venue: "Carbonic Coffee",
    tags: ["CodeDiversity", "Social", "Coffee Chat"],
    status: "past",
    eventUrl: "https://www.meetup.com/techtank-to/events/305395398/",
    imagePath: "/images/meetup/highres_524928803.jpeg",
  },
  // ─── 2024 ────────────────────────────────────────────────────────────────────
  {
    id: "bits-bytes-bowties",
    title: "Bits, Bytes, and Bowties",
    pitch: "Holiday party celebrating two years of TechTank",
    date: "2024-12-14",
    tags: ["Anniversary", "Social", "Holiday"],
    status: "past",
    photoAlbum: photoAlbums["AF1QipNaxy4wPaRA3EwJOduVBxlFXvGGqBsDmYRoAFw7_ChOrWGOjRo8Kk1TKYA5tiaE6g"],
  },
  {
    id: "code-diversity-coffee-2024-12",
    title: "Code Diversity Monthly Coffee Chats",
    pitch: "Monthly coffee chat for women and non-binary folks in tech",
    date: "2024-12-14",
    time: "11:00 AM - 1:00 PM",
    venue: "Carbonic Coffee",
    tags: ["CodeDiversity", "Social", "Coffee Chat"],
    status: "past",
    eventUrl: "https://www.meetup.com/techtank-to/events/304806485/",
    imagePath: "/images/meetup/highres_524928803.jpeg",
  },
  {
    id: "wreck-the-rack",
    title: "Wreck the Rack: TechTank's Pool Hall Battle",
    pitch: "Competitive pool night for the tech community",
    date: "2024-11-16",
    tags: ["Sports", "Social"],
    status: "past",
    photoAlbum: photoAlbums["AF1QipOXFVlljbwPWfZ2MVv5rhWpTIaWzLb6Jdfp9aqRvtYP241OIvn3cbVMN-qooI1Fmg"],
  },
  {
    id: "code-diversity-coffee-2024-11",
    title: "Code Diversity Monthly Coffee Chats",
    pitch: "Monthly coffee chat for women and non-binary folks in tech",
    date: "2024-11-16",
    time: "11:00 AM - 1:00 PM",
    venue: "Carbonic Coffee",
    tags: ["CodeDiversity", "Social", "Coffee Chat"],
    status: "past",
    eventUrl: "https://www.meetup.com/techtank-to/events/304348630/",
    imagePath: "/images/meetup/highres_524471440.jpeg",
  },
  {
    id: "gen-ai-rag-fpa",
    title: "Fueling Growth: Generative AI & RAG Applications in FP&A",
    pitch: "How AI is transforming financial planning and analysis",
    date: "2024-11-14",
    time: "6:00 PM - 9:00 PM",
    venue: "Vena Solutions",
    tags: ["Tech Talk", "AI", "FinTech"],
    status: "past",
    eventUrl: "https://www.meetup.com/techtank-to/events/304263016/",
    youtubeVideo: youtubeVideos["2UTsy-Lbulk"],
    photoAlbum: photoAlbums["AF1QipMfuV2mdrwgETwmivv4zQUu8pSRAzOG0D9J6j4nCpnNDKPMAgWL5ru6sYqMaMOOQg"],
  },
  {
    id: "edtech-ai-accessibility",
    title: "EdTech at the Crossroads: AI, Accessibility, and the Evolving Classroom",
    pitch: "Panel discussion on the future of education technology",
    date: "2024-10-28",
    time: "6:00 PM - 9:00 PM",
    venue: "Rakuten Kobo",
    tags: ["Panel", "EdTech", "AI", "Accessibility"],
    status: "past",
    eventUrl: "https://www.meetup.com/techtank-to/events/303655206/",
    youtubeVideo: youtubeVideos["N50r7eIEIS0"],
    photoAlbum: photoAlbums["AF1QipMwzeGDJqNkRSSagw_D8v3F73XeaPR9kmpQcpYjHCCuMx7nZ94feDaTGMA55whrLg"],
  },
  {
    id: "cypress-overwhelmed-dev",
    title: "Cypress for the Overwhelmed Developer",
    pitch: "Practical Cypress testing for developers who feel behind on testing",
    date: "2024-10-01",
    time: "7:00 PM - 9:00 PM",
    venue: "Online",
    tags: ["Tech Talk", "Testing", "Web Dev"],
    status: "past",
    eventUrl: "https://www.meetup.com/techtank-to/events/303601353/",
    imagePath: "/images/meetup/highres_523676979.jpeg",
  },
  {
    id: "forensics-rsc",
    title: "The Forensics of React Server Components",
    pitch: "Deep dive into how RSC actually works",
    date: "2024-09-18",
    time: "6:00 PM - 9:00 PM",
    venue: "Points.com",
    tags: ["Tech Talk", "React", "Web Dev"],
    status: "past",
    eventUrl: "https://www.meetup.com/techtank-to/events/302940980/",
    youtubeVideo: youtubeVideos["NOlSKs5PLpM"],
    photoAlbum: photoAlbums["AF1QipMPoK9UuL4g8MKPP8Tk8tI2FTppYtQQ-Nf0ga6DZXjFmqXT5SHTYikca8rhmltqhg"],
  },
  {
    id: "code-diversity-coffee-2024-09",
    title: "Code Diversity Monthly Coffee Chats",
    pitch: "Monthly coffee chat for women and non-binary folks in tech",
    date: "2024-09-14",
    time: "11:00 AM - 1:00 PM",
    venue: "Carbonic Coffee",
    tags: ["CodeDiversity", "Social", "Coffee Chat"],
    status: "past",
    eventUrl: "https://www.meetup.com/techtank-to/events/303330348/",
    imagePath: "/images/meetup/highres_521950379.jpeg",
  },
  {
    id: "fyre-festival",
    title: "Fyre Festival",
    pitch: "TechTank's infamous summer social",
    date: "2024-09-07",
    tags: ["Social"],
    status: "past",
    photoAlbum: photoAlbums["AF1QipMgtyV8CNEuz-qajiP1CHJXhOThudbAQwu8JRpN_OSpPnjsb1H8PBPNI1old3yukQ"],
  },
  {
    id: "ai-insights-experts",
    title: "Unlocking AI: In-Depth Insights from Leading Experts",
    pitch: "Panel with AI industry leaders",
    date: "2024-08-15",
    time: "6:00 PM - 9:00 PM",
    venue: "1 Roof Garden Lane",
    tags: ["Panel", "AI"],
    status: "past",
    eventUrl: "https://www.meetup.com/techtank-to/events/302337555/",
    youtubeVideo: youtubeVideos["RUco7XrbMqk"],
    photoAlbum: photoAlbums["AF1QipMlGtrOSia0VXZaDqAcjItENfxwXFdxJO2A9QCKGwXcRPn46nY5e_DB9puMgfky9Q"],
  },
  {
    id: "code-diversity-coffee-2024-08",
    title: "Code Diversity Monthly Coffee Chats",
    pitch: "Monthly coffee chat for women and non-binary folks in tech",
    date: "2024-08-10",
    time: "11:00 AM - 1:00 PM",
    venue: "Carbonic Coffee",
    tags: ["CodeDiversity", "Social", "Coffee Chat"],
    status: "past",
    eventUrl: "https://www.meetup.com/techtank-to/events/302503778/",
    imagePath: "/images/meetup/highres_521950379.jpeg",
  },
  {
    id: "tank-sports-2024",
    title: "Tank Sports",
    pitch: "Multi-sport summer event",
    date: "2024-08-10",
    tags: ["Sports", "Social"],
    status: "past",
    photoAlbum: photoAlbums["AF1QipNm1fut4HKxSRTpQ-6RkNQDkXsrzHhYfCaQwkoZAOWpw6b64L3iLU1yA3MHl_r8aQ"],
  },
  {
    id: "tankolympics",
    title: "TankOlympics",
    pitch: "Olympic-themed games and competitions",
    date: "2024-07-27",
    tags: ["Sports", "Social"],
    status: "past",
    photoAlbum: photoAlbums["AF1QipMaV0hBrR-eYX20MmtDBemZSZGUE3Y_kvO0JF9Cfm4crS27KpoU9tuY2u1aGNXWAA"],
  },
  {
    id: "mini-webpack-scratch",
    title: "Building a Mini Webpack from Scratch",
    pitch: "Understand how bundlers work by building one yourself",
    date: "2024-07-16",
    time: "6:00 PM - 9:00 PM",
    venue: "225 King St W",
    tags: ["Tech Talk", "Web Dev", "JavaScript"],
    status: "past",
    eventUrl: "https://www.meetup.com/techtank-to/events/301699806/",
    imagePath: "/images/meetup/highres_521809945.jpeg",
  },
  {
    id: "softball-sashimis-2024",
    title: "Softball Sashimi's",
    pitch: "Summer softball game",
    date: "2024-07-13",
    tags: ["Sports", "Social"],
    status: "past",
    photoAlbum: photoAlbums["AF1QipMmBy4aNt0rNAsHwMagst6jvo93awXW5yyWd4yCw9g5u0vdHpN7BRRHedJ8ofNEpQ"],
  },
  {
    id: "code-diversity-coffee-2024-07",
    title: "Code Diversity Monthly Coffee Chats",
    pitch: "Monthly coffee chat for women and non-binary folks in tech",
    date: "2024-07-13",
    time: "11:00 AM - 1:00 PM",
    venue: "Carbonic Coffee",
    tags: ["CodeDiversity", "Social", "Coffee Chat"],
    status: "past",
    eventUrl: "https://www.meetup.com/techtank-to/events/301852269/",
    imagePath: "/images/meetup/highres_521950379.jpeg",
  },
  {
    id: "sausages-cause-bbq",
    title: "Sausages for a Cause BBQ",
    pitch: "Charity BBQ event",
    date: "2024-06-15",
    tags: ["Social", "Charity"],
    status: "past",
    photoAlbum: photoAlbums["AF1QipNM9FBTNWpRR8DWT99MItot1HtgKiLEccHtwjYZIXBqPyQa8s4-ATrTlPNbCjf1gA"],
  },
  {
    id: "networking-101-2024",
    title: "Networking 101",
    pitch: "How to network effectively in the tech industry",
    date: "2024-06-04",
    time: "7:00 PM - 9:00 PM",
    venue: "Online",
    tags: ["Tech Talk", "Career", "Networking"],
    status: "past",
    eventUrl: "https://www.meetup.com/techtank-to/events/301198832/",
    imagePath: "/images/meetup/highres_521252023.jpeg",
  },
  {
    id: "engineering-wellness-2024",
    title: "Engineering Wellness: Innovations and Challenges in Health Tech",
    pitch: "Exploring how technology is transforming healthcare delivery",
    date: "2024-05-16",
    time: "6:00 PM - 9:00 PM",
    venue: "1 Roof Garden Lane",
    tags: ["Tech Talk", "HealthTech", "Panel"],
    status: "past",
    eventUrl: "https://www.meetup.com/techtank-to/events/300591167/",
    imagePath: "/images/meetup/highres_520941912.jpeg",
  },
  {
    id: "ai-prompting-101",
    title: "AI Prompting 101",
    pitch: "Fundamentals of prompt engineering for developers",
    date: "2024-05-14",
    time: "7:00 PM - 9:00 PM",
    venue: "Online",
    tags: ["Tech Talk", "AI", "Beginner-friendly"],
    status: "past",
    eventUrl: "https://www.meetup.com/techtank-to/events/300782288/",
    imagePath: "/images/meetup/highres_520806256.jpeg",
  },
  {
    id: "anniversary-social-2024",
    title: "Anniversary Social",
    pitch: "Celebrating one year of TechTank",
    date: "2024-04-20",
    tags: ["Anniversary", "Social"],
    status: "past",
    photoAlbum: photoAlbums["AF1QipN5YllsNHTVeUJKlSnd8bD4jyTo6muTTiMdHifF3DhT0olsYLxMbHynTtJ8jHJ7Uw"],
  },
  {
    id: "epic-quest-javascript",
    title: "The Epic Quest of Javascript through Time and Cyberspace",
    pitch: "A sweeping history of JavaScript's evolution and where it's headed",
    date: "2024-04-24",
    time: "6:00 PM - 9:00 PM",
    venue: "482 Front St W",
    tags: ["Tech Talk", "JavaScript", "Web Dev"],
    status: "past",
    eventUrl: "https://www.meetup.com/techtank-to/events/300175753/",
    imagePath: "/images/meetup/highres_520152027.jpeg",
  },
  {
    id: "pathfinders-2024",
    title: "Pathfinders: Celebrating Diversity and Innovation in Tech",
    pitch: "Panel celebrating diverse paths and perspectives in the tech industry",
    date: "2024-03-26",
    time: "6:00 PM - 9:00 PM",
    venue: "Cohere",
    tags: ["Panel", "CodeDiversity", "Career"],
    status: "past",
    eventUrl: "https://www.meetup.com/techtank-to/events/299326496/",
    imagePath: "/images/meetup/highres_519276676.jpeg",
  },
  {
    id: "accessible-nav-menus",
    title: "It's more than a <nav>: Making accessible navigation menus",
    pitch: "Practical guide to building accessible navigation for the web",
    date: "2024-03-05",
    time: "7:00 PM - 9:00 PM",
    venue: "Online",
    tags: ["Tech Talk", "Accessibility", "Web Dev"],
    status: "past",
    eventUrl: "https://www.meetup.com/techtank-to/events/299380715/",
    imagePath: "/images/meetup/highres_519308057.jpeg",
  },
  {
    id: "generative-ai-developers-2024",
    title: "Generative AI for Developers",
    pitch: "Hands-on introduction to building with generative AI tools",
    date: "2024-02-22",
    time: "6:00 PM - 9:00 PM",
    venue: "Microsoft Reactor Toronto",
    tags: ["Tech Talk", "AI", "Workshop"],
    status: "past",
    eventUrl: "https://www.meetup.com/techtank-to/events/298712672/",
    imagePath: "/images/meetup/highres_518649638.jpeg",
  },
  {
    id: "coding-with-character",
    title: "Coding with Character",
    pitch: "How character and ethics shape better software engineers",
    date: "2024-02-21",
    time: "8:00 PM - 10:00 PM",
    venue: "Online",
    tags: ["Tech Talk", "Career", "Culture"],
    status: "past",
    eventUrl: "https://www.meetup.com/techtank-to/events/299017176/",
    imagePath: "/images/meetup/highres_518943016.jpeg",
  },
  {
    id: "containerization-101",
    title: "Containerization 101: Docker and Beyond",
    pitch: "Demystifying Docker and container orchestration for developers",
    date: "2024-02-13",
    time: "7:00 PM - 9:00 PM",
    venue: "Online",
    tags: ["Tech Talk", "DevOps", "Docker"],
    status: "past",
    eventUrl: "https://www.meetup.com/techtank-to/events/298854685/",
    imagePath: "/images/meetup/highres_518949413.jpeg",
  },
  {
    id: "css-chronicles-2024",
    title: "CSS Chronicles: Navigating the Newest CSS Features",
    pitch: "A tour of the latest CSS features shipping in modern browsers",
    date: "2024-02-01",
    time: "6:00 PM - 9:00 PM",
    venue: "Intuit Canada",
    tags: ["Tech Talk", "CSS", "Web Dev"],
    status: "past",
    eventUrl: "https://www.meetup.com/techtank-to/events/298329281/",
    imagePath: "/images/meetup/highres_518418480.jpeg",
  },
  {
    id: "cottage-trip",
    title: "Cottage Trip",
    pitch: "Winter getaway for the community",
    date: "2024-02-17",
    tags: ["Social", "Trip"],
    status: "past",
    photoAlbum: photoAlbums["AF1QipOdL17zISJwXuA-sOQpNz71wSZ5plWDiQ112VjuKLxMFMX3hLObJUJ6v5J_c-asHA"],
  },
  {
    id: "burnout-in-tech",
    title: "Rekindling the Flame: Navigating and Overcoming Burnout in Tech",
    pitch: "Honest conversation about burnout, recovery, and sustainable engineering",
    date: "2024-01-30",
    time: "8:00 PM - 10:00 PM",
    venue: "Online",
    tags: ["Tech Talk", "Career", "Wellness"],
    status: "past",
    eventUrl: "https://www.meetup.com/techtank-to/events/298283794/",
    imagePath: "/images/meetup/highres_518284688.jpeg",
  },
  {
    id: "feature-flagging-primer",
    title: "There's a Flag for That! A Developer's Primer on Feature Flagging",
    pitch: "How feature flags enable safer deployments and experimentation",
    date: "2024-01-09",
    time: "7:00 PM - 9:00 PM",
    venue: "Online",
    tags: ["Tech Talk", "DevOps", "Engineering"],
    status: "past",
    eventUrl: "https://www.meetup.com/techtank-to/events/298165707/",
    imagePath: "/images/meetup/highres_518139051.jpeg",
  },
  // ─── 2023 ────────────────────────────────────────────────────────────────────
  {
    id: "figma-devmode-workshop",
    title: "Figma Workshop: Devmode Tips and Tricks",
    pitch: "Level up your Figma workflow with Dev Mode features",
    date: "2023-12-05",
    time: "7:00 PM - 9:00 PM",
    venue: "Online",
    tags: ["Tech Talk", "Design", "Workshop"],
    status: "past",
    eventUrl: "https://www.meetup.com/techtank-to/events/297602552/",
    imagePath: "/images/meetup/highres_517574457.jpeg",
  },
  {
    id: "app-performance-deep-dive",
    title: "You've deployed... But how is your app performing?",
    pitch: "Monitoring, observability, and performance tuning for production apps",
    date: "2023-11-30",
    time: "6:00 PM - 9:00 PM",
    venue: "Rakuten Kobo",
    tags: ["Tech Talk", "DevOps", "Performance"],
    status: "past",
    eventUrl: "https://www.meetup.com/techtank-to/events/297145894/",
    imagePath: "/images/meetup/highres_517035730.jpeg",
  },
  {
    id: "transitioning-fullstack",
    title: "Transitioning to Full Stack and Beyond: Broadening Your Tech Horizons",
    pitch: "Strategies for developers looking to expand across the full stack",
    date: "2023-11-22",
    time: "8:00 PM - 10:00 PM",
    venue: "Online",
    tags: ["Tech Talk", "Career", "Full Stack"],
    status: "past",
    eventUrl: "https://www.meetup.com/techtank-to/events/297176805/",
    imagePath: "/images/meetup/highres_517192330.jpeg",
  },
  {
    id: "cracking-a11y-code",
    title: "Cracking the A11y Code: Web Accessibility Basics for Beginners",
    pitch: "Practical introduction to making your web apps more accessible",
    date: "2023-11-07",
    time: "8:00 PM - 10:00 PM",
    venue: "Online",
    tags: ["Tech Talk", "Accessibility", "Beginner-friendly"],
    status: "past",
    eventUrl: "https://www.meetup.com/techtank-to/events/296957170/",
    imagePath: "/images/meetup/highres_516817887.jpeg",
  },
  {
    id: "niagara-glen-hike",
    title: "Niagara Glen Hike",
    pitch: "Fall hike at Niagara Glen",
    date: "2023-10-28",
    tags: ["Social", "Outdoors"],
    status: "past",
    photoAlbum: photoAlbums["AF1QipOg2itOXIvPeeQKFEFScI2UCeOojdcuGpMGoJXJftFFaKlCVDhzhdkk2PNfrICpzA"],
  },
  {
    id: "halloween-2023",
    title: "Halloween",
    pitch: "Spooky season social",
    date: "2023-10-31",
    tags: ["Social", "Holiday"],
    status: "past",
    photoAlbum: photoAlbums["AF1QipMbVRHwXl8qR8eWRaxk0jqxbUxRBD4ic1arOmYFPQQNPaFonrTiGJU4pf_rfFFMxg"],
  },
  {
    id: "llms-what-how",
    title: "Large Language Models: What Are They And How Do We Use Them?",
    pitch: "Demystifying LLMs for developers building the next wave of AI apps",
    date: "2023-10-23",
    time: "6:00 PM - 9:00 PM",
    venue: "Cohere",
    tags: ["Tech Talk", "AI", "LLM"],
    status: "past",
    eventUrl: "https://www.meetup.com/techtank-to/events/296408305/",
    imagePath: "/images/meetup/highres_516203971.jpeg",
  },
  {
    id: "junior-to-midlevel",
    title: "From Junior to Mid-Level & Beyond: Strategies for Career Advancement",
    pitch: "Real talk from engineers who made the leap — and what actually helped",
    date: "2023-10-18",
    time: "8:00 PM - 10:00 PM",
    venue: "Online",
    tags: ["Tech Talk", "Career", "Beginner-friendly"],
    status: "past",
    eventUrl: "https://www.meetup.com/techtank-to/events/296505054/",
    imagePath: "/images/meetup/highres_516306438.jpeg",
  },
  {
    id: "website-performance-deep-dive",
    title: "Loading... A deep dive into website and web app performance",
    pitch: "Tools, techniques, and mental models for faster web experiences",
    date: "2023-09-28",
    time: "6:00 PM - 9:00 PM",
    venue: "Points.com",
    tags: ["Tech Talk", "Performance", "Web Dev"],
    status: "past",
    eventUrl: "https://www.meetup.com/techtank-to/events/295642016/",
    imagePath: "/images/meetup/highres_515354669.jpeg",
  },
  {
    id: "bowling-2023",
    title: "Bowling",
    pitch: "Where it all began",
    date: "2023-09-16",
    tags: ["Sports", "Social"],
    status: "past",
    photoAlbum: photoAlbums["AF1QipNJf7YltaKvL5Cq_bX4O8Nt0heaFeetF1UuqVj54JoxVEzjPm4F85nQPHj_LDKpdw"],
  },
  {
    id: "continuous-learning-tech",
    title: "Embracing Continuous Learning: Navigating Skill Development in Tech",
    pitch: "How to keep growing in a fast-moving industry without burning out",
    date: "2023-09-06",
    time: "8:00 PM - 10:00 PM",
    venue: "Online",
    tags: ["Tech Talk", "Career", "Learning"],
    status: "past",
    eventUrl: "https://www.meetup.com/techtank-to/events/295750233/",
    imagePath: "/images/meetup/highres_515481840.jpeg",
  },
];

export function getUpcomingEvents(): Event[] {
  return events
    .filter((e) => e.status === "upcoming")
    .sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime());
}

export function getPastEvents(): Event[] {
  return events
    .filter((e) => e.status === "past")
    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
}

export function getRecentEvents(count: number = 4): Event[] {
  return getPastEvents().slice(0, count);
}
